version: '3.7'

services:
  api:
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://*:8080
    ports:
      - 8080:8443/tcp
  db:
    environment:
      SA_PASSWORD: Your_password123
      ACCEPT_EULA: Y
    ports:
      - 1433:1433/tcp
  cache:
    ports:
    - 6379:6379/tcp