version: '3.7'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:8080
    ports:
      - "8888:80/tcp"
  db:
    ports:
    - "1433:1433/tcp"