version: '3.7'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://*:8443
    ports:
      - "8443:8443/tcp"
  db:
    ports:
    - "1433:1433/tcp"